services:
  postgres-db:
    image: postgres:latest # 建议指定一个明确的版本标签，例如 postgres:16
    container_name: xiaozhi-postgres
    environment:
      POSTGRES_USER: root        # 设置超级用户的用户名
      POSTGRES_PASSWORD: 123456  # 设置超级用户的密码
      POSTGRES_DB: chat_db      # (可选) 自动创建一个初始数据库
    ports:
      - "5432:5432" # 将主机的5432端口映射到容器的5432端口
    volumes:
      - xiaozhi-postgres-data:/var/lib/postgresql/data # 将数据持久化到命名的卷中
    restart: no # 容器退出时不自动重启

volumes:
  xiaozhi-postgres-data:
    driver: local # 定义一个命名的卷用于持久化存储